services:
  - type: web
    name: zalo-bot-ppp-service
    env: docker
    plan: free
    envVars:
      - key: ZALO_BOT_TOKEN
        value: "1175912593990733827:IQHQDAkiFOfwODzTmEKdPvfCSbDJubszVeLXcvxwqTSZXPbNaBaTLYQAmeXpAWMX"
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "false"
      - key: PORT
        value: "5678"
